# 第5章 语句

* 复合语句【块】 用花括号括起来的语句和声明的序列 不以分号作为结束。
* 语句作用域 定义在控制结构中的变量只能在响应的语句内部可见 语句结束 变量超作用范围

## 流程控制语句

* if语句块使用规范 

  * 注意花括号与缩进
  * 注意块的位置
  * 注意悬垂else 在多个if里 与最近的尚未匹配的if匹配

* switch

  * case 的值必须是整数常量表达式

  * 在命中case之后 会一直执行直到一个break语句

  * 一般情况下 下一个case标签之前应该有一个break

  * 可以执行多个case语句来共享操作 case 甚至可以不换行 <font color =#0000FF>此处有点懵逼</font>

    ```c++
    switch(a)
    {
    	case 1:case 2:case 3:...
    		expr;
    		break;
    }
    ```

  * 如果case跨标签执行 该case之前的部分会被忽略掉。如果一个带有初值的变量位于作用域之外,另一个在作用域之内,则从前一处跳转到后一处的行为是非法的

    ```C++
    case true:
    	//因为程序的执行流程可能绕开下面的初始化语句,所以该switch语句不合法
        string file_name;//错误:控制流绕过一个隐式初始化的变量
        int ival=0;//错误:控制流绕过一个显式初始化的变量
        int jval;//正确:因为jva1没有初始化	
        break;
    case false:
    	//正确:jva1虽然在作用域内,但是它没有被初始化
        jval=next_num();//正确:给jval赋一个值
        if(file_name.empty())//file_name在作用域内,但是没有被初始化
    //.
    ```

    > 假设上述代码合法,则一旦控制流直接跳到false分支,也就同时略过了变量file name和iva1的初始化过程。此时这两个变量位于作用域之内,跟在false之后的代码试图在尚未初始化的情况下使用它们,这显然是行不通的。因此C++语言规定,不允许跨过变量的初始化语句直接跳转到该变量作用域内的另一个位置。

  * 如果需要为某个case分支定义并初始化一个变量,我们应该把变量定义在块内,从而确保后面的所有case标签都在变量的作用域之外。

## 循环语句

* while(expr)

*  传统for

  ```c++
  //for(初始化,检查语句,更新语句)
  for (init-statemen;condition; expression)
  	statement
  ```

  * 执行顺序

      1. 先执行一次 init-statemen
      2. 执行一次condition
      3. 如果条件为真 执行for循环体内部内同
      4. 执行更新语句expression

  * init-statement也可以定义多个对象所有变量的基础类型必须相同
  
  * for 可以省略三条语句中的任一一个或全部
  
* 范围for语句 <font color=#FF0000 bold=True><b>C++11 新特性</b></font>

  ```C++
  for(declaration:expression)
  	statement
  ```

  * expression表示的必须是一个序列,拥有能返回迭代器的begin和end成员
  * declaration定义一个变量,序列中的每个元素都得能转换成该变量的类型。确保类型相容最简单的办法是使用auto类型说明符,这、如果需要对序列中的元素执行写操作,循环变量必须声明成引用类型。
  * 每次迭代都会重新定义循环控制变量,并将其初始化成序列中的下一个值,之后才会执行statement。
  * 禁止在范围for里为遍历的容器添加新的值

* do while 先做再执行

## 跳转语句

* break 中止最近的while,do while,for,switch

* continue 中止最近的一次循环当前迭代并开始下一次

* go to  不要用

  ```C++
  go to label;
  end: ...
  ```

## 异常处理

* **throw**表达式(throw expression),异常检测部分使用throw表达式来表示它遇到了无法处理的问题。我们说throw引发(raise)了异常。

* **try** 语句块(try block),异常处理部分使用try 语句块处理异常。try语句块以关键字try开始,并以一个或多个**catch**子句(catch clause)结束。try 语句块中代码抛出的异常通常会被某个catch子句处理。因为catch子句"处理"异常,所以它们也被称作异常处理代码(exception handler)。

  ``` c++
  try{
  	program-statements
  } catch (exception-declaration){
  	handler-statements
  } catch (exception-declaration){
  	handler-statements
  }//...
  ```

  

* 一套异常类(exception class),用于在throw表达式和相关的catch子句之间传递异常的具体信息。

  > 寻找处理代码的过程与函数调用链刚好相反。当异常被抛出时,首先搜索抛出该异常的函数。如果没找到匹配的catch子句,终止该函数,并在调用该函数的函数中继续寻找。如果还是没有找到匹配的catch子句,这个新的函数也被终止,继续搜索调用它的函数。以此类推,沿着程序的执行路径逐层回退,直到找到适当类型的catch子句为止。如果最终还是没能找到任何匹配的 catch子句,程序转到名为terminate的标准库函数。该函数的行为与系统有关,一般情况下,执行该函数将导致程序非正常退出。

* 标准异常

  异常头文件	

  * exception头文件定义了最通用的异常类exception。它只报告异常的发生,不提供任何额外信息。

  * stdexcept头文件定义了几种常用的异常类,详细信息在表5.1中列出。

  * new头文件定义了bad alloc异常类型

  * type info 头文件定义了bad_cast异常类型

    <stdexcept>定义的异常类|说明
    ---|---
    exception|最常见的问题
    runtime error|只有在运行时才能检测出的问题
    range error |运行时错误:生成的结果超出了有意义的值域范围
    overflow_error|运行时错误:计算上溢
    underflow_error|运行时错误:计算下溢
    1ogic_error|程序逻辑错误
    domain_error|逻辑错误:参数对应的结果值不存在
    invalid_argument|逻辑错误:无效参数
    1ength_error|逻辑错误:试图创建一个超出该类型最大长度的对象
    out_of_range|逻辑错误:使用一个超出有效范围的值